from eclipse-mosquitto
# MQTT Changes the permissions of config file, which then cannot be checked into git ... thats why we generate it here
RUN echo "allow_anonymous true" >> /mosquitto/config/mosquitto.conf && echo "listener 1883 0.0.0.0" >> /mosquitto/config/mosquitto.conf
