name: Create and publish a Docker image

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  release:
    types: [created]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Image Name
        id: image_tag_lower
        run: |
          IMAGE_TAG="${{ env.REGISTRY }}/${{ github.repository }}:"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            IMAGE_TAG+="latest"
          else
            RELEASE_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
            IMAGE_TAG+="$RELEASE_NAME"
          fi
          # Make Lowercase
          IMAGE_TAG=$(echo $IMAGE_TAG | awk '{print tolower($0)}')
          # Append to output
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.image_tag_lower.outputs.IMAGE_TAG }}
          target: prod
